#!/usr/bin/env bash
# vi: ft=sh
set -x
source ~/.config/setup.d/.lib.sh

pushd ~/.config

disp "Installing dependencies..."

pkg ruby &> /dev/null
pkg fish &> /dev/null
gem install github &> /dev/null
gem install gist &> /dev/null

for fn in ~/.config/setup.d/*; do
    NAME=$(basename $fn)
    DIDIT="${HOME}/.config/setup.d/.complete_${NAME}"
    if [ ! -f $DIDIT ]; then
	    read -p "Configure $fn? [y/N] " DOIT
	    if [ "$DOIT" = "y" ]; then
		    . $fn
		    touch $DIDIT
	    fi
	fi
done


