#!/usr/bin/env bash
# vi: ft=sh
source ~/.config/setup.d/.lib.sh

pushd ~/.config

disp "Installing dependencies..."
install vim tmux git fish most &> /dev/null

for fn in ~/.config/setup.d/*; do
    NAME=$(basename $fn)
    read -p "Configure $fn? [y/N] " DOIT
    if [ "$DOIT" = "y" ]; then
        bash $fn
    fi
done


