#!/usr/bin/env bash
# vi: ft=sh
source ~/.config/setup.d/.lib.sh

pushd ~/.config

disp "Installing dependencies..."
pkg ruby tree most &> /dev/null
gem install github &> /dev/null
gem install gist &> /dev/null

for fn in ~/.config/setup.d/*; do
    NAME=$(basename $fn)
    read -p "Configure $fn? [y/N] " DOIT
    if [ "$DOIT" = "y" ]; then
        . $fn
    fi
done


