#!/usr/bin/env bash
# vi: ft=sh
source ~/.config/setup/.lib.sh

if [ -d ~/.vim ]; then
    disp "REMOVING original ~/.vim dir"
    rm -rf ~/.vim
fi

if [ -f $MYVIMRC ]; then
    disp "REMOVING original ~/.vimrc"
    rm -rf $MYVIMRC
fi

echo "source ${CONF}/vim/rc.vim" > $MYVIMRC
