#!/usr/bin/env bash
# vi: ft=sh
source ~/.config/setup.d/.lib.sh

pkg git
disp "Installed git"

git config --global user.email "chexers.775@gmail.com"
git config --global user.name "Chex Possible"

gist --login

echo "Git configured"
