#!/usr/bin/env bash
# vi: ft=sh
source $LIB

[ -z `which git` ] && pkg git
git config --global user.email "chexers.775@gmail.com"
git config --global user.name "Chex Possible"

[ -x gist ] && gist --login

echo "Git configured"
