#!/usr/bin/env bash
source ~/.config/setup.d/.lib.sh
pkg most tmux

ENV="$HOME/.config/env.sh"
echo ". $ENV" >> $HOME/.bashrc
disp "Added ENVIRONMENT"
source $ENV

FSH=$(which fish)
disp "Configuring shell..."
disp "Changing default shell to $FSH"
sudo chsh -s `which fish` `whoami`

disp "Installing fish addon 'bass'..."
BASS="https://github.com/edc/bass"
DEST=/tmp/`whoami`-bass
rm -rf $DEST/*
github clone edc bass $DEST
pushd $DEST
make install
popd

echo "Installing tmuxinator"
sudo apt install -y ruby
sudo gem install tmuxinator
echo "source-file ~/.config/tmux.conf" > ~/.tmux.conf
echo -e"\nSHELL CONFIGURED"

FSH=`which fish`
TC="${HOME}/.tmux.conf"

if [ -f $TC ]; then
    mv $TC "${TC}.old"
    disp "Moved old tmux conf out the way"
fi
ln -s ~/.config/tmux.conf $TC
echo -e "\nset-option -g default-shell \"$FSH\"" | tee -a $TC

disp "Configured tmux"



