#!/usr/bin/env bash
source ~/.config/setup.d/.lib.sh

. ~/.config/setup.d/shell-editor

. ~/.config/setup.d/shell-pager

. ~/.config/setup.d/shell-mux

ENV="$HOME/.config/env.sh"
echo ". $ENV" >> $HOME/.bashrc
disp "Added ENVIRONMENT"
source $ENV

disp "Installing fish addon 'bass'..."
BASS="https://github.com/edc/bass"
DEST=/tmp/`whoami`-bass
rm -rf $DEST/*
git clone "${BASS}.git" $DEST
pushd $DEST
make install
popd
