#!/usr/bin/env bash
# vi: ft=sh
source ~/.config/setup.d/.lib.sh

pkg vim

if [ -d ~/.vim ]; then
    rm -rf ~/.vim
    disp "REMOVED original ~/.vim dir"
fi

if [ -e $MYVIMRC ]; then
    rm -rf $MYVIMRC
    disp "REMOVED original ~/.vimrc"
fi

disp "Adding personal config to vimrc"
echo "source ${CONF}/vim/rc.vim" > $MYVIMRC

pushd ~/.config/
disp "Cloning plugins"
git submodule init
git submodule update
